# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the local requirements file
COPY requirements.local.txt .

# Install any needed packages specified in requirements.local.txt
RUN pip install --no-cache-dir -r requirements.local.txt

# Copy the rest of the application code
COPY . .

# Set the default command to open a bash shell
CMD ["/bin/bash"]