_wandb:
    value:
        cli_version: 0.21.3
        e:
            d8em4vo8mkdtoncmmt7x01bnr33j4fce:
                args:
                    - --train
                    - encoder
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "470328393728"
                        used: "125817884672"
                email: gs25049@gs.hs.kr
                executable: /src/gs25049/.conda/envs/research/bin/python3
                git:
                    commit: 9b6b1bedfd39b10af8be663704ef95c7a456af01
                    remote: https://github.com/don-gik/model_v.0.2.git
                gpu: NVIDIA RTX A6000
                gpu_count: 10
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-77968020-254a-c770-f5ac-e50e84d2b0fc
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-f6b31a4e-b948-de1c-4899-84ee0e862c47
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-757b0146-898d-d644-0051-69a95f23c913
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-6ce5b13c-ed2f-0faa-9cc0-129d9148f958
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-09c860f2-ddcb-4947-a95b-76b8a0565006
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-6de7418a-de63-62a8-eb9a-82abf78000a8
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-c2691b2f-fe07-3f9b-b693-103a317c6018
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-f1ada295-9050-884f-cacb-f056d826cc51
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-ed443a61-76e5-8a79-e838-be06fa6fb856
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-4ea3da58-91f4-8509-daff-c162e6b70639
                host: cslab
                memory:
                    total: "1014202114048"
                os: Linux-5.4.0-216-generic-x86_64-with-glibc2.31
                program: /src/gs25049/last_rae/model_v.0.2/main.py
                python: CPython 3.11.13
                root: /src/gs25049/last_rae/model_v.0.2
                startedAt: "2025-09-10T03:18:28.393743Z"
                writerId: d8em4vo8mkdtoncmmt7x01bnr33j4fce
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 49
                - 71
            "2":
                - 1
                - 49
                - 71
            "4": 3.11.13
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
